# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            Kitty McGurk
tagline:          'Your tagline'
description:      Student journalist and entrepreneur at the University of Iowa with a future in Marketing, Communications, and Advertising. 
url:              http://mcgurk.github.io
baseurl:          /profile-mcgurk/
shortbaseurl:     /profile-mcgurk
colorscheme:      ''
#options '' (black), theme-base-08 (red), theme-base-09 (orange), theme-base-0a (yellow), theme-base-0b (green), theme-base-0c (cyan), theme-base-0d (blue), theme-base-0e (magenta), theme-base-0f (brown)


author:
  name:           'Kitty McGurk'
  url:            ''
  
paginate:         5

# Custom vars
version:          0.8.1

